const getSales = async(req, res, next) => {
    try{
        
    } catch(error){
        next(error)
    }
}

export { 
    getSales
}